name: Website
description: The novo.ws Website
version: 1.0.0
homepage: https://www.novo.ws
author: Novo Work Systems <i@novo.ws>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  sass_builder: any
